money:
  name1: 'Ent'
  name2: 'Lor'
  name3: 'Und'
  name4: 'Rie'

citybanks:
  barkhaven:
    balance: '0.0'
    taxes: '0.0'
    unpaid:
      - ''

  marblehold:
    balance: '0.0'
    taxes: '0.0'
    unpaid:
      - ''

jobs:
  janitor:
    title: 'janitor'
    pay:
      1st:
      2nd:
      3rd:
      4th:
    permission: 'dremoney.jobpay.janitor'
